baseURL = 'https://www.hristo-georgiev.com/'
languageCode = 'en-us'
theme = "hugo-coder"
title = "Hristo Georgiev"
defaultContentLanguage = "en"

[params]
author = "Hristo Georgiev"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Hristo Georgiev's Personal Website"
keywords = "website,engineer,personal"
info = ["Engineer"]
avatarURL = "images/avatar.jpg"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2024

faviconSVG = "images/favicon.svg"
favicon_32 = "images/favicon-32x32.png"
favicon_16 = "images/favicon-16x16.png"
# Git Commit in Footer, uncomment the line below to enable it
#commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languages such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []


# [params.cloudflare]
# token = "token"

[params.googleTagManager]
id = "364581604"

# If you want to use Yandex Metrika(https://metrika.yandex.ru) for analytics, add this section
# [params.yandexMetrika]
# id = "gid"

# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'", "https://www.youtube.com"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/",
# ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/hggeorgiev"

# [[params.social]]
# name = "Gitlab"
# icon = "fa-brands fa-gitlab fa-2x"
# weight = 2
# url = "https://gitlab.com/johndoe/"

# [[params.social]]
# name = "Twitter"
# icon = "fa-brands fa-x-twitter fa-2x"
# weight = 3
# url = "https://twitter.com/johndoe/"

# [[params.social]]
# name = "LinkedIn"
# icon = "fa-brands fa-linkedin fa-2x"
# weight = 4
# url = "https://www.linkedin.com/in/johndoe/"

# [[params.social]]
# name = "Medium"
# icon = "fa-brands fa-medium fa-2x"
# weight = 5
# url = "https://medium.com/@johndoe"

# [[params.social]]
# name = "RSS"
# icon = "fa-solid fa-rss fa-2x"
# weight = 6
# url = "https://myhugosite.com/index.xml"
# rel = "alternate"
# type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

# [[languages.en.menu.main]]
# name = "Contact"
# weight = 2
# url = "contact/"

